# Generated by Django 2.2 on 2019-07-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listing_id',
            new_name='id_listing',
        ),
    ]
