# Generated by Django 2.2 on 2019-07-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190729_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='id_listing',
            new_name='ListingID',
        ),
    ]
