# Generated by Django 2.2 on 2019-07-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190729_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ListingID',
            new_name='listing_id',
        ),
    ]
