# Generated by Django 2.2 on 2019-07-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190721_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
